### ISSUE TITLE
Pouvoir signaler qu'un projet est terminé

### ISSUE THREAD

**Issue by virgile-dev** [opendemocracynow/opendemocracynow.github.io#4]
Rajouter une variable Jekyll pour pouvoir signaler le statut d'un projet.
La variable devrait pouvoir s'appliquer sur le listing des projets dans /projets et sur les pages dédiées. 

Qu'en penses-tu @arthur-koenig ?

**Comment by opendemocracynow** [comment]
Oui c'était dans la Todo list au début, et puis ça s'est volatilisé :) Tu
penses à quoi comme statut? stade d'avancement par exemple?

2016-08-31 19:28 GMT+02:00 virgile-dev <notifications@github.com>:

**Comment by virgile-dev** [comment]
Juste pouvoir mettre une pastille ```Terminé``` 
En vrai j'y ai réfléchi je pense que ça suffit :)

**Comment by opendemocracynow** [comment]
Ça roule, je regarde ça

**Comment by virgile-dev** [comment]
Merci!
